### ISSUE TITLE
Publish the manifest on flathub

### ISSUE THREAD

**Issue by mujx** [vrutkovs/flatpak-nheko#1]
Thanks a lot for talking the time to put this together! 

Would it be possible to submit it in flathub to be more easily accessible?

**Comment by vrutkovs** [comment]
Uhm, sure thing, although the build system needs to be improved to simplify patching.

I'll rework it (any suggestions are welcome too) and submit a flathub request

**Comment by mujx** [comment]
Let me know (or submit a PR) about the improvements you have in mind regarding the build system. One improvement that was made recently is that there are flags that you can use to point to the third-party deps (i.e no need to download them during the build).

**Comment by qazip** [comment]
Any news regarding this @vrutkovs? It would be cool to be ablet o install nheko via flatpak.

**Comment by mujx** [comment]
Closing, as I've already opened a PR in flathub.
